# Generated by Django 4.2.28 on 2026-03-18 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Наименование')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='categories/', verbose_name='Изображение')),
                ('alt_image', models.CharField(blank=True, max_length=200, verbose_name='Подпись к изображению')),
            ],
            options={
                'verbose_name': 'Вид животного',
                'verbose_name_plural': 'Виды животных',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Наименование')),
                ('description', models.TextField(verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('price', models.DecimalField(decimal_places=3, max_digits=9, verbose_name='Цена')),
                ('discount', models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='Скидка')),
                ('in_stock', models.BooleanField(default=True, verbose_name='В наличии')),
                ('rating', models.FloatField(default=0, verbose_name='Рейтинг')),
                ('thumbnail', models.ImageField(blank=True, upload_to='', verbose_name='Изображение товара')),
                ('category', models.CharField(blank=True, choices=[('Cages', 'Клетки и домики'), ('Food', 'Корма и лакомства'), ('Vitamin', 'Витамины и минералы'), ('Toys', 'Игрушки'), ('Scratching post', 'Когтеточки'), ('Comb', 'Щетки и пуходерки'), ('Aquarium', 'Химия для аквариума'), ('Filler', 'Наполнители')], max_length=30, verbose_name='Категория')),
                ('size', models.CharField(blank=True, choices=[('Small', 'Мелкий'), ('Medium', 'Средний'), ('Large', 'Крупный')], max_length=20, verbose_name='Размер животного')),
                ('animal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogue.animal', verbose_name='Вид животного')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/', verbose_name='Изображение')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='images', to='catalogue.product')),
            ],
            options={
                'verbose_name': 'Изображение товара',
                'verbose_name_plural': 'Изображения товаров',
            },
        ),
    ]
