# Generated by Django 4.2.28 on 2026-03-20 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_cart_user_wishlist_wishlistitem_cartitem_cart_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='settings',
            field=models.JSONField(blank=True, default=dict, verbose_name='Настройки'),
        ),
    ]
