# Generated by Django 6.0.3 on 2026-04-05 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0004_category_alter_cart_options_alter_cartitem_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='registered_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
    ]
