# Generated by Django 6.0.3 on 2026-05-27 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0009_alter_product_thumbnail_alter_user_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='product',
        ),
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
