# Generated by Django 6.0.3 on 2026-05-28 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0010_remove_review_product_remove_review_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlistitem',
            name='wishlist',
        ),
        migrations.RemoveField(
            model_name='wishlistitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Wishlist',
        ),
        migrations.DeleteModel(
            name='WishlistItem',
        ),
    ]
